//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moodary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1b04a7d7_549a_454d_aef6_e3bfc47cdde2 {
            get {
                object obj = ResourceManager.GetObject("1b04a7d7-549a-454d-aef6-e3bfc47cdde2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20260320_1725_Image_Generation_remix_01km58z29pf5db6j2fvrydt11r {
            get {
                object obj = ResourceManager.GetObject("20260320_1725_Image Generation_remix_01km58z29pf5db6j2fvrydt11r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20260320_2036_Moonlit_Dreamscape_remix_01km5kywccec7rwf07dmcsa839 {
            get {
                object obj = ResourceManager.GetObject("20260320_2036_Moonlit Dreamscape_remix_01km5kywccec7rwf07dmcsa839", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20260321_1953_Image_Generation_remix_01km83v9czfayag8bvfb4gaaey {
            get {
                object obj = ResourceManager.GetObject("20260321_1953_Image Generation_remix_01km83v9czfayag8bvfb4gaaey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20260408_2107_Image_Generation_remix_01knpk7swxfsgvpb3726adxfb5 {
            get {
                object obj = ResourceManager.GetObject("20260408_2107_Image Generation_remix_01knpk7swxfsgvpb3726adxfb5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _57166a67_fd05_4e75_a653_961b24594083 {
            get {
                object obj = ResourceManager.GetObject("57166a67-fd05-4e75-a653-961b24594083", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5f6134ac_edff_4875_85f3_bfb0644a9a1f_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("5f6134ac-edff-4875-85f3-bfb0644a9a1f-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6ae99000_6765_480e_8ad8_5cfd6771745d_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("6ae99000-6765-480e-8ad8-5cfd6771745d-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7ec0e7e9_4ced_4ce5_a0b6_75bd66a21ecd_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("7ec0e7e9-4ced-4ce5-a0b6-75bd66a21ecd-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap account_setting_icon_symbol_design_illustration_vector_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("account-setting-icon-symbol-design-illustration-vector-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b0a7a200e5e72cc4cb11ad06cdac6557 {
            get {
                object obj = ResourceManager.GetObject("b0a7a200e5e72cc4cb11ad06cdac6557", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cc039011_8553_4583_93d1_b7f57fe733c5_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("cc039011-8553-4583-93d1-b7f57fe733c5-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
